[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true
  [redirects.headers]
    "Content-Type" = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "Content-Security-Policy" = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.gemini.com https://generativelanguage.googleapis.com https://*.espn.com https://api.the-odds-api.com https://api.sportsdata.io; img-src 'self' data: https:; manifest-src 'self'"
    "X-Frame-Options" = "DENY"
    "X-Content-Type-Options" = "nosniff"
    "X-XSS-Protection" = "1; mode=block"
    "Referrer-Policy" = "strict-origin-when-cross-origin"
    "Permissions-Policy" = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    "Content-Type" = "application/manifest+json"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"
    "Cache-Control" = "public, max-age=0, must-revalidate"
    "Service-Worker-Allowed" = "/"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css; charset=utf-8"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.css"
  [headers.values]
    "Content-Type" = "text/css; charset=utf-8"
    "Cache-Control" = "public, max-age=3600"

[[headers]]
  for = "/*.svg"
  [headers.values]
    "Content-Type" = "image/svg+xml; charset=utf-8"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    "Content-Type" = "image/svg+xml; charset=utf-8"
    "Cache-Control" = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

# Forms handling
[forms]
  enabled = true

# Dev server settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"